version: '3'

services:
  web:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres

    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    networks:
      - dbmate
    volumes:
      - data:/var/lib/psql


volumes:
  data:

networks:
  dbmate: