version: '3'

services:
  web:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - .env
    hostname: postgres
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_IN_DOCKER}
    networks:
      - dbmate
      - app
    volumes:
      - data:/var/lib/psql


volumes:
  data:

networks:
  dbmate:
  app: 